service:
  name: ignitecertificate
plugins:
  - serverless-offline
  - serverless-webpack
provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
functions:
  hello:
    handler: src/functions/hello.handle
    events:
      - http:
          path: /hello
          method: GET
          cors: true